options:
  lang: en-US

languages:
  en-US:
    console:
      registering-geo: "Registering geo resources..."
      loading-items: "Loading items..."
      loading-researches: "Loading researches..."
      addon-enabled: "Enabled Magic8Ball addon"
      addon-disabled: "Disabled Magic8Ball addon"
      loading-language: "Loading language..."
      loaded-language: "Loaded language:"
    item-groups:
      main:
        name: "&eMagic 8 Ball"
        lore: ""
    items:
      M8BALL_FRAGMENT:
        name: "&fMagic &68 &fBall &bFragment"
        lore:
          - ""
          - "Emits traces of &6knowledge"
          - ""
      M8BALL_ITEM:
        name: "&fMagic &68 &fBall"
        lore:
          - ""
          - "&fCan answer anything..."
          - "&f...maybe. My sources say so."
          - ""
          - "&eLeft Click&7 air to use"
          - "&eRight Click&7 a block to use"
          - ""
    responses:
      affirmative:
        - "It is certain"
        - "It is decidedly so"
        - "Without a doubt"
        - "Yes, definitely"
        - "You may rely on it"
        - "As I see it, yes"
        - "Most likely"
        - "Outlook good"
        - "Yes"
        - "Signs point to yes"
      noncommittal:
        - "Reply hazy, try again"
        - "Ask again later"
        - "Better not tell you now"
        - "Cannot predict now"
        - "Concentrate and ask again"
      negative:
        - "Don't count on it"
        - "My reply is no"
        - "My sources say no"
        - "Outlook not so good"
        - "Very doubtful"
